### ISSUE TITLE
Model is not managed

### ISSUE THREAD

**Issue by agouliel** [andrewgodwin/yamdl#2]
I am getting the below error: 

File ".venv/lib/python3.11/site-packages/yamdl/loader.py", line 57, in get_model_class
    raise ValueError(
ValueError: Cannot load yamdl fixture - the model name myapp.talk is not managed.

even though I have set the attribute in the model:
<img width="641" alt="Screenshot 2022-11-04 at 17 17 42" src="https://user-images.githubusercontent.com/5585850/200037979-330e7b64-15ec-4873-ab41-eb01404825d7.png">

**Comment by andrewgodwin** [comment]
Is the app in `INSTALLED_APPS`? If it is, then what does the following show you when run in `manage.py shell`?

```
import django.apps
django.apps.apps.get_models()
```

**Comment by agouliel** [comment]
Shell doesn't start either (same error).

**Comment by andrewgodwin** [comment]
Remove the yamdl settings to run that shell command then - it will just tell you what models Django knows you have.

**Comment by agouliel** [comment]
Fixed it. I had included yamdl in INSTALLED_APPS, but hadn't included my own app. Silly. Thank you!
