### ISSUE TITLE
Allow to define model directory name on model

### ISSUE THREAD

**Issue by rixx** [andrewgodwin/yamdl#3]
I'm looking into getting yamdl running on an existing project, and I'd prefer it if I didn't have to rename my existing directories to the `appname.modelname` naming. Something like `Meta.yamdl_directory = "foo"` sounds like it could be idiomatic and nice to use.

*Edit:* Something like [ff6e836](https://github.com/rixx/yamdl/commit/ff6e836e6a5610b38a1544155afbfb1822cff769), happy to open a PR if this is something you want.

**Comment by andrewgodwin** [comment]
I will happily take a PR for this!
